% perform hash regression using hashing codes generated by different methods
function hashRegression (task)

  for dataset = task.datasetList
    dataset = dataset{1};

    try
      fprintf('Performing evaluation task %s on %s\n', task.name, dataset.name);
      dataset = loadDataset(task, dataset);

      for cidx = 1: length(task.codeLengths)
        codeLength = task.codeLengths(cidx);
        nMethod = length(task.methodList);

        for midx = 1: nMethod
          method = task.methodList{midx};

          try

            % compute binary codes
            fprintf('Computing binary codes on dataset %s using %s (%d bits)\n', dataset.name, method.name, codeLength);
            cacheFile = sprintf('%s/code_%s_%s_%d.mat', task.cacheDir, dataset.name, method.name, codeLength);
            if loadCache(cacheFile, task.forceFresh, getConst('CACHE_VER_CODE'))
              addpath(method.path);
              [B1, B2, timeTrain, timeTest] = method.hash(task, dataset, method, codeLength);
              rmpath(method.path);
              save(cacheFile, 'version', 'B1', 'B2', 'timeTrain', 'timeTest', '-v7.3');
            end
            fprintf('  Time cost: %.4gs (training), %.4g (testing)\n', timeTrain, timeTest);

            % perform hash regression using Hamming distance
            for ridx = 1: length(task.regresserList)
              regresser = task.regresserList{ridx};
              fprintf('Perform hash regression on dataset %s using %s and %s (%d bits)\n', dataset.name, method.name, regresser.name, codeLength);
              cacheFile = sprintf('%s/hashRegression_%s_%s_%s_%d.mat', task.cacheDir, dataset.name, method.name, regresser.name, codeLength);
              if loadCache(cacheFile, task.forceFresh, getConst('CACHE_VER_HASH_REGRESSION'))
                addpath(regresser.path);
                tp = timerStart();
                V1 = dataset.value(dataset.indexTrain);
                V2 = dataset.value(dataset.indexTest);
                [predict, succ] = regresser.regression(regresser, B1, B2, V1);
                succRate = sum(succ) / length(V2);
                RMSE = sqrt(mean((predict(succ) - V2(succ)) .^ 2));
                timeCost = timerStop(tp);
                rmpath(regresser.path);
                save(cacheFile, 'version', 'predict', 'succ', 'succRate', 'RMSE', 'timeCost', '-v7.3');
              end
              fprintf('  Root mean squared error: %.4g\n', RMSE);
              fprintf('  Success rate: %.4g\n', succRate);
              fprintf('  Time cost: %.4gs (elapsed), %.4gs (CPU)\n', timeCost.etime, timeCost.ctime);
            end

          catch err
            reportError(err, sprintf('Error when performing evaluation task %s on dataset %s using %s (%d bits)\n', task.name, dataset.name, method.name, codeLength));
          end

        end

      end

      fprintf('\n\n');

    catch err
      reportError(err, sprintf('Error when performing evaluation task %s on %s\n', task.name, dataset.name));
    end

  end

end
